CSharp_Web_Cinema_App/CinemaApp.Web/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using Microsoft.EntityFrameworkCore;

using CinemaApp.Data;
using CinemaApp.Data.Models;
using CinemaApp.Web.ViewModels.Movie;
using static CinemaApp.Common.EntityValidationConstants.Movie;

namespace CinemaApp.Web.Controllers
{
    public class MovieController : BaseController
    {
        private readonly CinemaDbContext dbContext;

        public MovieController(CinemaDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet] // Action to run with GET request from Index 
        public async Task<IActionResult> Index()
        {
            IEnumerable<Movie> allMovies = await this.dbContext.Movies.ToArrayAsync();

            return this.View(allMovies);  // this obj will be pass to Views >> Movie >> Index
        }

        [HttpGet]  // This action need to return the form where data will be inserted
        public async Task<IActionResult> Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddMovieInputModel inputModel)
        {

            bool isReleasedDateValid = DateTime.TryParseExact(inputModel.ReleaseDate, ReleaseDateFormat, CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime releaseDate);

            if (!isReleasedDateValid)
            {
                // Will return the same view "Create" with the same wrong model data!
                this.ModelState.AddModelError(nameof(inputModel.ReleaseDate), String.Format("The Release Date is not in correct format {0}.", ReleaseDateFormat));
                return View(inputModel);
            }

            if (!this.ModelState.IsValid)
            {
                // Will return the same view "Create" with the same wrong model data!
                return View(inputModel);
            }

            Movie validatedMovie = new Movie()
            {
                Title = inputModel.Title,
                Genre = inputModel.Genre,
                ReleaseDate = releaseDate,
                Director = inputModel.Director,
                Duration = inputModel.Duration,
                Description = inputModel.Description,
                ImageUrl = inputModel.ImageUrl, 
            };

            await this.dbContext.Movies.AddAsync(validatedMovie);
            await this.dbContext.SaveChangesAsync();
            return this.RedirectToAction(nameof(Index));
        }

        [HttpGet]  // This action need to return the form where data will be inserted
        public async Task<IActionResult> Details(string? id)
        {
            Guid guidId = Guid.Empty;

            bool isGuidValid = this.IsGuidIdValid(id, ref guidId);

            if (!isGuidValid)
            {
                return RedirectToAction(nameof(Index));
            }

            Movie? movie = await this.dbContext.Movies.FirstOrDefaultAsync(x => x.Id == guidId);

            if (movie == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return this.View(movie);
        }

        [HttpGet]
        public async Task<IActionResult> AddToProgram(string? id)
        {
            Guid movieGuid = Guid.Empty;

            bool isGuidValid = this.IsGuidIdValid(id, ref movieGuid);

            if (!isGuidValid)
            {
                return this.RedirectToAction(nameof(Index));
            }

            Movie? movie = await this.dbContext.Movies.FirstOrDefaultAsync(x => x.Id == movieGuid);

            if (movie == null)
            {
                return this.RedirectToAction(nameof(Index));
            }

            AddMovieToCinemaInputModel viewModel = new AddMovieToCinemaInputModel()
            {
                MovieId = movie.Id.ToString(),
                MovieTitle = movie.Title,
                Cinemas = await this.dbContext.Cinemas
                .Include(x => x.CinemaMovies)
                .ThenInclude(x => x.Movie)
                .Select(x => new CinemaCheckBoxItemInputModel()
                {
                    Id = x.Id.ToString(),
                    Name = x.Name,
                    Location = x.Location,
                    IsSelected = x.CinemaMovies.Any(x => x.Movie.Id == movieGuid)
                })
                .ToArrayAsync()
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddToProgram(AddMovieToCinemaInputModel model)
        {

            if (this.ModelState.IsValid == false)
            {
                return this.View(model);
            }

            Guid movieGuid = Guid.Empty;

            bool isGuidValid = this.IsGuidIdValid(model.MovieId, ref movieGuid);

            if (isGuidValid == false)
            {
                return this.RedirectToAction(nameof(Index));
            }

            Movie? movie = await this.dbContext.Movies.FirstOrDefaultAsync(x => x.Id == movieGuid);

            if (movie == null)
            {
                return this.RedirectToAction(nameof(Index));
            }

            ICollection<CinemaMovie> entitiesToAdd = new HashSet<CinemaMovie>();

            foreach (CinemaCheckBoxItemInputModel cinemaInputModel in model.Cinemas)
            {
                Guid cinemaGuid = Guid.Empty;

                bool isCinemaGuidValid = this.IsGuidIdValid(cinemaInputModel.Id, ref cinemaGuid);

                if (isCinemaGuidValid == false)
                {
                    this.ModelState.AddModelError(string.Empty, "Invalid cinema");
                    return this.View(model);
                }

                Cinema? cinema = await this.dbContext.Cinemas.FirstOrDefaultAsync(x => x.Id == cinemaGuid);

                if (cinema == null)
                {
                    this.ModelState.AddModelError(string.Empty, "Invalid cinema");
                    return this.View(model);
                }

                CinemaMovie? cinemaMovie = await this.dbContext.CinemaMovies.FirstOrDefaultAsync(x => x.MovieId == movieGuid && x.CinemaId == cinemaGuid);

                if (cinemaInputModel.IsSelected == true)
                {
                    if (cinemaMovie == null)
                    {
                        entitiesToAdd.Add(new CinemaMovie()
                        {
                            Cinema = cinema,
                            Movie = movie,
                        });

                    }
                    else
                    {
                        cinemaMovie.IsDeleted = false;   
                    }
                }
                else
                {
                    if (cinemaMovie != null) 
                    {
                        cinemaMovie.IsDeleted = true;
                    }
                }

                await this.dbContext.SaveChangesAsync();

            }

            await this.dbContext.CinemaMovies.AddRangeAsync(entitiesToAdd);
            await this.dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Cinema");

        }
    }
}

CSharp_Web_Cinema_App/CinemaApp.Web/Controllers/WatchlistController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using CinemaApp.Data;
using CinemaApp.Data.Models;
using CinemaApp.Web.ViewModels.Watchlist;

using static CinemaApp.Common.EntityValidationConstants.Movie;
using Microsoft.AspNetCore.Authorization;


namespace CinemaApp.Web.Controllers
{
    [Authorize] // If not Authorized (userId == null) will redirect to the login Index
    public class WatchlistController : BaseController
    {
        private readonly CinemaDbContext dbContext;
        private readonly UserManager<ApplicationUser> userManager;

        public WatchlistController(CinemaDbContext dbContext, UserManager<ApplicationUser> userManager)
        {
            this.dbContext = dbContext;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            string userId = this.userManager.GetUserId(User)!;

            IEnumerable<ApplicationUserWatchlistViewModel> watchlistViewModels = await this.dbContext.UsersMovies.Where(x => x.ApplicationUser.Id.ToString().ToLower() == userId.ToLower())
                .Include(x => x.Movie)
                .Select(x => new ApplicationUserWatchlistViewModel
                {
                    MovieId = x.MovieId.ToString(),
                    Title = x.Movie.Title,
                    Genre = x.Movie.Genre,
                    ReleaseDate = x.Movie.ReleaseDate.ToString(ReleaseDateFormat),
                    ImageUrl = x.Movie.ImageUrl!,
                })
                .ToListAsync();

            return View(watchlistViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> AddToWatchlist(string? movieId)
        {
            Guid movieGuid = Guid.Empty;

            if (IsGuidIdValid(movieId, ref movieGuid) == false)
            {
                return RedirectToAction("Index", "Movie");
            }

            Movie? movie = await this.dbContext.Movies.FirstOrDefaultAsync(x => x.Id == movieGuid);

            if (movie == null)
            {
                return RedirectToAction("Index", "Movie");
            }

            Guid userGuid = Guid.Parse(this.userManager.GetUserId(User)!);

            bool addedToWatchlistAlready = await dbContext.UsersMovies
                .AnyAsync(x => x.ApplicationUserId == userGuid && x.MovieId == movieGuid);

            if (addedToWatchlistAlready == false)
            {
                ApplicationUserMovie userMovie = new ApplicationUserMovie()
                {
                    MovieId = movieGuid,
                    ApplicationUserId = userGuid,
                };

                await this.dbContext.UsersMovies.AddAsync(userMovie);
                await dbContext.SaveChangesAsync();

            }

            return this.RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromWatchlist(string movieId)
        {
            Guid movieGuid = Guid.Empty;

            if (IsGuidIdValid(movieId, ref movieGuid) == false)
            {
                return RedirectToAction("Index", "Movie");
            }

            Movie? movie = await this.dbContext.Movies.FirstOrDefaultAsync(x => x.Id == movieGuid);

            if (movie == null)
            {
                return RedirectToAction("Index", "Movie");
            }

            Guid userGuid = Guid.Parse(this.userManager.GetUserId(User)!);

            ApplicationUserMovie? existingInWatchlist = await dbContext.UsersMovies
                .FirstOrDefaultAsync(x => x.ApplicationUserId == userGuid && x.MovieId == movieGuid);

            if (existingInWatchlist != null)
            {
                this.dbContext.UsersMovies.Remove(existingInWatchlist);
                await dbContext.SaveChangesAsync();
            }

            return this.RedirectToAction(nameof(Index));

        }
    }
}

CSharp_Web_Cinema_App/CinemaApp.Web/Views/Movie/AddToProgram.cshtml
@using CinemaApp.Web.ViewModels.Movie;
@using CinemaApp.Web.ViewModels.Cinema;

@model AddMovieToCinemaInputModel;

@{
    ViewData["Title"] = "Add Movies";
}

<h2>Add @Model.MovieTitle to Cinema Program</h2>

<form asp-action="AddToProgram" method="post">
    <input type="hidden" asp-for="MovieId" />
    <input type="hidden" asp-for="MovieTitle" />
   


    <h3>Select Cinemas:</h3>

    <div class="form-group">
        @for (var i = 0; i < Model.Cinemas.Count; i++)
        {
            <div class="form-check">

                <input type="hidden" asp-for="@Model.Cinemas[i].Id" />
                <input type="hidden" asp-for="@Model.Cinemas[i].Name" />
                 <input type="hidden" asp-for="@Model.Cinemas[i].Location" />
                <input type="checkbox" asp-for="@Model.Cinemas[i].IsSelected" class="form-check-input" />
                <label class="form-check-label">@Model.Cinemas[i].Name, @Model.Cinemas[i].Location</label>
            </div>
        }
    </div>

    <button type="submit" class="btn btn-primary">Confirm</button>
</form>

<a asp-action="Index" class="btn btn-secondary mt-3">Back to Movies</a>

CSharp_Web_Cinema_App/CinemaApp.Web/Views/Movie/Create.cshtml
@using CinemaApp.Web.ViewModels.Movie;
@model AddMovieInputModel; // this is showing what model "type" will this view accept!

<h2>Add a New Movie</h2>

<form asp-action="Create" method="post">
    @*This FORM has method >> post*@
    <div>
        <label asp-for="Title">Movie Name</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>   @* In this span asp-validation-for will return the error message from the validation method*@
    </div>
    <div>
        <label asp-for="Genre">Genre</label>
        <input asp-for="Genre" class="form-control" />
        <span asp-validation-for="Genre" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="ReleaseDate">Release Date</label>
        <input asp-for="ReleaseDate" class="form-control" />
        <span asp-validation-for="ReleaseDate" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Duration">Duration (minutes)</label>
        <input asp-for="Duration" class="form-control" />
        <span asp-validation-for="Duration" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Director">Director</label>
        <input asp-for="Director" class="form-control" />
        <span asp-validation-for="Director" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Description">Description</label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="ImageUrl">Image URL</label>
        <input asp-for="ImageUrl" class="form-control" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Create Movie</button>
</form>

<a asp-action="Index">Back to Movies List</a>

CSharp_Web_Cinema_App/CinemaApp.Web/Views/Movie/Details.cshtml
@using CinemaApp.Data.Models;
@model Movie;

<h2>@Model.Title</h2>

<p><strong>Genre:</strong> @Model.Genre</p>
<p><strong>Release Date:</strong> @Model.ReleaseDate.ToString("MMMM yyyy")</p>
<p><strong>Duration:</strong> @Model.Duration minutes</p>
<p><strong>Director:</strong> @Model.Director</p>
<p><strong>Description:</strong> @Model.Description</p>

<a asp-action="Index" class="btn btn-primary">Back to All Movies</a>

CSharp_Web_Cinema_App/CinemaApp.Web/Views/Movie/Index.cshtml
@using CinemaApp.Data.Models;
@model IEnumerable<Movie> // this is showing what model "type" will this view accept!

@*this.Model is the object coming from the MovieController IAction from Index()*@

<h2>All Movies</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Genre</th>
            <th>Release Date</th>
            <th>Duration</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Movie movie in this.Model)
        {
            <tr>
                <td>@movie.Title</td>
                <td>@movie.Genre</td>
                <td>@movie.ReleaseDate.ToString("MMMM yyyy")</td>
                <td>@movie.Duration minutes</td>
                <td>
                    <a asp-action="Details" asp-route-id="@movie.Id" class="btn btn-info">Details</a>
                    <a asp-action="AddToProgram" asp-route-id="@movie.Id" class="btn btn-info">Add to Program</a>

                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <form asp-controller="Watchlist" asp-action="AddToWatchlist" method="post" class="d-inline">
                            <input type="hidden" name="movieId" value="@movie.Id" />
                            <button type="submit" class="btn btn-warning">+Watchlist</button>
                        </form>
                    }

                </td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="Create" class="btn btn-primary">Add New Movie</a>